---
  - hosts: instances
    become: true
    vars:
      gitlab_external_url: "https://gitlab.cde-lab.cloud/"
      gitlab_redirect_http_to_https: "true"
      gitlab_ssl_certificate: "/etc/letsencrypt/live/gitlab.cde-lab.cloud/cert.pem"
      gitlab_ssl_certificate_key: "/etc/letsencrypt/live/gitlab.cde-lab.cloud/privkey.pem"
    roles:
      - { role: geerlingguy.gitlab }